// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cshzkslgkjuwdmfjcdzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_RVDXEbBr9ZRAD7PBUfR6ug_w2UqKxnu"
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
